### ISSUE TITLE
Create Deactivate_Flow task

### ISSUE THREAD

**Issue by apretorius** [SFDO-Tooling/CumulusCI#3413] opened 2022-10-27 17:21 UTC
### Feature Type

I'm interested in a new Task or Flow for CumulusCI.

### Does your feature request solve a current problem?

When loading data, using a Snowfakery recipe, some visual flows in the org fire and throw errors. These are valid, and not an issue with the flow, but it halts the data load process and requires you to manually go into the org to deactivate the flows.

### Describe the solution you'd like

I would like a task to be created called deactivate_flows (similar to activate_flows) that can be used to feed in a list of flows to turn off. Then you can build a flow that deactivates the flows, loads the data, and then reactivates them.

### Describe alternatives you've considered

Using UpdateData to update the status field on a list of flows returned from a SOQL query.

**Comment by davidmreed** [comment] 2022-10-27 20:19
I'm sorry, @apretorius, I did not realize when I asked you to open the issue that we already had this in the backlog. Closing as duplicate of https://github.com/SFDO-Tooling/CumulusCI/issues/3320.

**Closed by davidmreed** 2022-10-27 20:19 UTC
Labels: enhancement
