### ISSUE TITLE
Go To Record Home ${Project_Id} step is failing

### ISSUE THREAD

**Issue by pronitagrawalvera** [SFDO-Tooling/CumulusCI#1573] opened 2020-02-24 11:11 UTC
"CumulusCI/cumulusci/robotframework/locators_45.py /" requires a change at "actions": "css: ul.oneActionsRibbon"

Please update the xpath

**Comment by davisagli** [comment] 2020-02-24 16:12
@pronitagrawalvera Can you provide instructions for us to reproduce the issue? We have tests which use the Go To Record Home keyword with standard objects, which are passing. Is the problem that you are using it with a custom object with a custom Record Page that does not include the actions ribbon?

**Comment by pronitagrawalvera** [comment] 2020-02-25 05:14
Yes it is custom build, Do we have alternate keyword to replace"Go To Record Home"?

**Comment by davisagli** [comment] 2020-02-25 14:57
@boakley what would you suggest here?

**Comment by boakley** [comment] 2020-02-25 18:40
I'm not sure I have a suggestion, it's hard to know what the root cause of the failure is. I've never seen that error message before and don't know what's causing it. @pronitagrawalvera is it possible for you to give us more details? 

`Go to record home` is doing almost nothing more than building a URL that looks like **/lightning/r/_\<record id\>_/view**. @pronitagrawalvera does that sort of URL work for your custom object? Can you manually open a browser to the org and type in a URL in that form to get to the correct page?

**Comment by davisagli** [comment] 2020-02-25 18:47
@boakley I believe @pronitagrawalvera's problem is not with navigating to that URL, but the fact that keyword then waits for a locator which is not on the page, because it's a custom object with a custom record page that doesn't have the actions ribbon.

**Comment by pronitagrawalvera** [comment] 2020-02-26 05:22
Yes @davisagli you got it right, I have a issue with the locator("actions": "css: ul.oneActionsRibbon") which is define in the "CumulusCI/cumulusci/robotframework/locators_45.py /"

Navigation is not a issue, It is working fine.

**Comment by davidmreed** [comment] 2022-03-28 15:50
Closing issue due to old API version; if this issue is reproducible on current CumulusCI and Salesforce platform, please do reopen.

**Closed by davidmreed** 2022-03-28 15:50 UTC
