### ISSUE TITLE
2GP Package Version ID not added to local package registry

### ISSUE THREAD

**Issue by anspaujd** [SFDO-Tooling/CumulusCI#2090] opened 2020-10-14 17:09 UTC
**Describe the bug**
2GP Package ID is not added to local package registry upon creation. The new task command `create_package_version` runs successfully but doesn't add the new package version ID to the sfdx-project.json registry. This makes usage of the new package version impossible without manual interaction in the CLI. 

**Reproduction steps**
1. Open CCI project with local metadata
2. Run task command `cci task run create_package_version --org dev -o package_type Unlocked`

**Context**
- Your CumulusCI version (`3.20.1`).
- Your Python version (`Python 2.7.16`)
- MacOS version 10.15.7
- CCI installed via Brew

**Gist**
No gist available as command runs successfully but doesn't update local package registry.

**Comment by davisagli** [comment] 2020-10-14 19:53
This is by design: A key use case for us is building a package version for use in a continuous integration process. Since those builds will be triggered by commits, we don't want to make additional changes to the repository contents which then need to be committed.

Can you tell me more about the alternative to "manual interaction in the CLI" that you were hoping for? Are you using a non-command line tool that reads this info from sfdx-project.json?

**Comment by anspaujd** [comment] 2020-10-15 14:47
This ties to the other issue relating to creating Unlocked packages in the sense that if a customer has developed more than one package, they need to easily be able to pull the Package Version ID of the latest package for the `update_dependency` command. Couple this with a decentralized development team and the package ID becomes more essential.

For example, a customer I am working with has the following model:
- Package 1 (owned by central OIT)
   - private Git repo
- Package 2 (owned by BU1)
   - private Git repo
   - contains dependency on Package 1 
- Package 3 (owned by BU2) 
   - private Git repo

In this example, there are 2 main issues that lack of the ID is creating.
1) The `update_dependency` command struggles to poll the private git repo for any dependent information
2) The latest package version ID is not passed to the SFDX-Project.json requires complex workarounds or manual steps in order to get the latest version for usage.

The specific use case that I am working to test and implement for this customer would be as follows:
1. Package 1 released new package version
2. Package 2 is working on a new feature that is dependent on the new Package 1 version
    - Commit to feature__QA branch fires flow to create dev org with newly released Package 1 via MetaCI
    - If build is successful, fire a flow in Package 1 repo to promote new package for production release

The issue that I am having with the flows is that the Package Version ID is not substantiated or recorded anywhere within the project itself requiring additional steps to query / locate the package version. From my personal experience with CCI and SFDX packaging of any form, I have been unable to build cross-dependencies outside of production released packages.  Since these packages exist in separate Git repos, the dependency on the Package Version ID in the JSON string has been essential for cross repo workflows.

I could be going about this entirely wrong but as customers adopt 2GP Unlocked Packages more this becomes a larger pain point.

**Comment by davidmreed** [comment] 2022-01-28 21:19
@anspaujd I am going to close this issue as a bug, because this _is_ currently working as designed, but I would love to chat with you about ways in which the different approaches to package version management can be made more ergonomic.

**Closed by davidmreed** 2022-01-28 21:19 UTC
