### ISSUE TITLE
Newest version of dependencies shouldn't install for older versions

### ISSUE THREAD

**Issue by mbeaty-sf** [SFDO-Tooling/CumulusCI#1199] opened 2019-09-09 21:35 UTC
Newest dependencies are being installed, even when trying to install an older version.

I ran the flow: `cci flow run install_prod -o install_managed__version 3.39`

and was met with the errors:

```
[Failed]: Update of InstalledPackage npsp: Error: (Account.BDE_List_FS) In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found, Details: Account.BDE_List_FS: In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found
(Contact.BDE_List_FS) In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found, Details: Contact.BDE_List_FS: In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found
2019-09-09 12:51:28: Exception in task install_managed
Traceback (most recent call last):
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/salesforce_api/metadata.py", line 66, in __call__
    return self._process_response(response)
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/salesforce_api/metadata.py", line 483, in _process_response
    raise MetadataComponentFailure(log, response)
cumulusci.salesforce_api.exceptions.MetadataComponentFailure: Update of InstalledPackage npsp: Error: (Account.BDE_List_FS) In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found, Details: Account.BDE_List_FS: In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found
(Contact.BDE_List_FS) In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found, Details: Contact.BDE_List_FS: In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/core/flowrunner.py", line 221, in run_step
    task()
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/core/tasks.py", line 141, in __call__
    self.result = self._run_task()
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/tasks/salesforce/InstallPackageVersion.py", line 80, in _run_task
    self._retry()
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/core/tasks.py", line 177, in _retry
    self._try()
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/tasks/salesforce/InstallPackageVersion.py", line 84, in _try
    api()
  File "/usr/local/Cellar/cumulusci/2.5.7/libexec/lib/python3.7/site-packages/cumulusci/salesforce_api/metadata.py", line 70, in __call__
    response=response,
cumulusci.salesforce_api.exceptions.MetadataParseError: Could not process MDAPI response: Update of InstalledPackage npsp: Error: (Account.BDE_List_FS) In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found, Details: Account.BDE_List_FS: In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found
(Contact.BDE_List_FS) In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found, Details: Contact.BDE_List_FS: In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found

Error: Could not process MDAPI response: Update of InstalledPackage npsp: Error: (Account.BDE_List_FS) In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found, Details: Account.BDE_List_FS: In field: npe01__FirstDonationDate__c - no CustomField named Account.npe01__FirstDonationDate__c found
(Contact.BDE_List_FS) In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found, Details: Contact.BDE_List_FS: In field: npe01__Last_Donation_Date__c - no CustomField named Contact.npe01__Last_Donation_Date__c found
```

**Comment by davisagli** [comment] 2019-09-10 16:36
Even if we fix it so that it knows the correct historic dependency versions to install, it'll still be challenging to make this work properly because it would be trying to run with the present-day version of the flow configuration and unpackaged metadata. /cc @jlantz 

The best way to install an old version of NPSP is using the MetaDeploy installer because part of publishing a version of the installer includes pinning all the steps to specific git revisions. For example: https://install.salesforce.org/products/npsp/3.147 to get NPSP 3.147 ...but unfortunately this only goes back that far because that's when we launched MetaDeploy.

**Comment by davidmreed** [comment] 2022-01-28 21:31
Closing this issue as it is working as designed.

**Closed by davidmreed** 2022-01-28 21:31 UTC
