### ISSUE TITLE
Expired scratch org recreate flow doesn't automatically set a password

### ISSUE THREAD

**Issue by bethbrains** [SFDO-Tooling/CumulusCI#945] opened 2019-01-21 23:26 UTC
When a scratch org expires, the user attempts to run something against the org, and cci asks `Attempt to recreate the scratch org? [Y/n]:`, if the user enters Y, the new org is created without a password. The expected behavior would be the same as `cci org scratch`, which does by default generate a password.

**Comment by davisagli** [comment] 2019-01-22 01:04
Thanks -- I think this is a duplicate of #670 (which we still need to work on).

**Closed by davisagli** 2019-01-22 01:04 UTC
